# Generated by Django 4.1.7 on 2023-03-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
            ],
        ),
        migrations.CreateModel(
            name='RespostasCorreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=250, verbose_name='Resposta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostasIncorretas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostaa', models.CharField(max_length=250, verbose_name='Resposta 1')),
                ('respostab', models.CharField(max_length=250, verbose_name='Resposta 2')),
                ('respostac', models.CharField(max_length=250, verbose_name='Resposta 3')),
            ],
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('dificuldade', models.CharField(choices=[('f', 'Facil'), ('m', 'Medio'), ('d', 'Dificil')], max_length=10, verbose_name='Dificuldade')),
                ('justifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.justificativas')),
                ('respostacorreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.respostascorreta')),
                ('respostaincorreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.respostasincorretas')),
            ],
        ),
    ]
